apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "new-helm.fullname" . }}-config
data:
  appsettings.json: |
    {
      "App": {
        "Name": "{{ include "new-helm.name" . }}",
        "Environment": "{{ .Values.env.ASPNETCORE_ENVIRONMENT }}"
      },
      "Logging": {
         "LogLevel": {
           "Default": "Debug",
           "Microsoft.AspNetCore": "Debug"
          }
      },
      "Database": {
        "Postgres": "{{ .Values.database.postgresConnection }}"
      },
      "Redis": {
        "Connection": "{{ .Values.redis.connectionString }}"
      }
    }