apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: station-manager-ingress
  namespace: iels-api-dev
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /station-manager/$2
spec:
  ingressClassName: nginx-apis
  tls:
    - hosts:
        - apis.ielsportal.com
      secretName: cwa-tls-secret

  rules:
    - host: apis.ielsportal.com
      http:
        paths:
          - path: /station-manager(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: iels-station-api
                port:
                  number: 80
