trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: DOCKERHUB_USERNAME
    value: "$(dockerhubUser)"
  - name: DOCKERHUB_PASSWORD
    value: "$(dockerhubPass)"

  - name: AZURE_SUBSCRIPTION
    value: "iels-azure-connection"

  - name: RESOURCE_GROUP
    value: "iels-platform"
  - name: CONTAINERAPPS_ENV
    value: "station-env"
  - name: CONTAINERAPP_NAME
    value: "station-manager-api"

  - name: IMAGE_NAME
    value: "iels-station-manager"
  - name: IMAGE_TAG
    value: "$(Build.BuildId)"

  - name: WORKSPACE_ID
    value: "8225f0cf-6709-4c43-8185-713e419ff1aa"
  - name: WORKSPACE_KEY
    value: "$(workspaceKey)"

steps:
  # NuGet caching
  - task: Cache@2
    displayName: "Cache NuGet packages"
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/*.csproj'
      restoreKeys: |
        nuget | "$(Agent.OS)"
      path: ~/.nuget/packages

  - task: UseDotNet@2
    displayName: "Install .NET SDK"
    inputs:
      packageType: "sdk"
      version: "10.0.x"

  # Restore + publish using cached packages
  - script: |
      dotnet restore
      dotnet publish -c Release -o out
    displayName: "Build .NET API"

  - task: DockerInstaller@0
    displayName: "Install Docker"

  # Docker layer caching
  - task: Cache@2
    displayName: "Cache Docker layers"
    inputs:
      key: 'docker | "$(Agent.OS)"'
      path: /tmp/.docker-cache

  - script: |
      echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin

      docker build \
        --cache-from /tmp/.docker-cache \
        --tag $(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG) .

      docker save $(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG) -o /tmp/.docker-cache

      docker push $(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG)
    displayName: "Build & Push Docker Image"

  - task: AzureCLI@2
    displayName: "Deploy to Azure Container Apps"
    inputs:
      azureSubscription: "$(AZURE_SUBSCRIPTION)"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az extension add --name containerapp --upgrade

        az containerapp env create \
          --name $(CONTAINERAPPS_ENV) \
          --resource-group $(RESOURCE_GROUP) \
          --location "uksouth" \
          --logs-workspace-id $(WORKSPACE_ID) 

        az containerapp create \
          --name $(CONTAINERAPP_NAME) \
          --resource-group $(RESOURCE_GROUP) \
          --environment $(CONTAINERAPPS_ENV) \
          --image $(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG) \
          --ingress external \
          --target-port 8080 \
          --query properties.configuration.ingress.fqdn
